name: Copy PR to another repository

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  copy_pr:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source repository
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        repository: ${{ github.event.pull_request.head.repo.pr-test-1 }}

    - name: Create fork of destination repository
      run: |
        curl -X POST \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          https://api.github.com/repos/rajneesh111/pr-test-2/forks

    - name: Checkout destination repository
      uses: actions/checkout@v2
      with:
        repository: rajneesh111/pr-test-2

    - name: Checkout PR branch
      run: |
        git checkout -b pr-branch origin/${{ github.event.pull_request.head.ref }}

    - name: Push changes to destination repository
      run: |
        git push --force-with-lease origin pr-branch

    - name: Create pull request on destination repository
      uses: peter-evans/create-pull-request@v3.10.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "Copy PR from source repository"
        title: ${{ github.event.pull_request.title }}
        body: ${{ github.event.pull_request.body }}
        base: master
        branch: pr-branch

