
name: auto generate new pr from latest merge
on:
  pull_request:
    branches: ["main"]
jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - name: Merge
      uses: KeisukeYamashita/auto-pull-request-merge@v1
      with:
        repository: rajneesh111/pr-test-2
        token: ${{ secrets.ACCESS_KEY }}
        intervalSeconds: 10
        timeoutSeconds: 60

