
name: auto generate new pr from latest merge
on:
  pull_request_target:
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: send Merge as PR
        run: |
          echo: $(git rev-parse --short "$GITHUB_SHA")

