name: Auto merge
on: pull_request
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: Create Comment
        uses: KeisukeYamashita/create-comment@v1
     
        with:
          intervalSeconds: 1
          timeoutSeconds: 60
          labels: test
          labelsStrategy: atLeastOne
          ignoreLabels: ignore
          comment: ${{ steps.merge.outputs.merged }}
