
name: auto generate new pr from latest merge
on:
  pull_request_target:
    types:
      - closed
jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: send Merge as PR
        uses: KeisukeYamashita/auto-pull-request-merge@v1
        with:
          repository: pr-test-2
          token: ${{ secrets.ACCESS_KEY }}
          intervalSeconds: 10
          timeoutSeconds: 60

